locals {
  build_timestamp = "${legacy_isotime("20060102150405")}"
  http_directory  = "${path.root}\\..\\scripts\\ubuntu\\2004"
}

source "virtualbox-iso" "autogenerated_1" {
  boot_command            = ["<esc><esc><esc><esc>e<wait>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "linux /casper/vmlinuz --- autoinstall ds=\"nocloud-net;seedfrom=http://{{ .HTTPIP }}:{{ .HTTPPort }}/\"<enter><wait>", "initrd /casper/initrd<enter><wait>", "boot<enter>", "<enter><f10><wait>"]
  boot_wait               = "5s"
  cpus                    = "${var.cpus}"
  disk_size               = "${var.disk_size}"
  guest_additions_path    = "VBoxGuestAdditions_{{ .Version }}.iso"
  guest_additions_url     = "${var.guest_additions_url}"
  guest_os_type           = "Ubuntu_64"
  hard_drive_interface    = "sata"
  headless                = "${var.headless}"
  http_directory          = "${local.http_directory}"
  iso_checksum            = "${var.iso_checksum}"
  iso_url                 = "${var.mirror}/${var.mirror_directory}/${var.iso_name}"
  memory                  = "${var.memory}"
  output_directory        = "${var.build_directory}/packer-${var.template}-virtualbox"
  shutdown_command        = "echo 'vagrant' | sudo -S shutdown -P now"
  ssh_password            = "vagrant"
  ssh_port                = 22
  ssh_timeout             = "10000s"
  ssh_username            = "vagrant"
  virtualbox_version_file = ".vbox_version"
  vm_name                 = "${var.template}"
}

build {
  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "shell" {
    execute_command = "echo '${var.ssh_password}' | {{ .Vars }} sudo -E -S sh '{{ .Path }}'"
    inline          = ["echo '========================================================================================================================'", "echo 'Adding vagrant to sudoers list ...'", "echo 'vagrant ALL=NOPASSWD:ALL' > /etc/sudoers.d/vagrant", "echo 'Install vagrant SSH key ...'", "mkdir -pm 700 /home/vagrant/.ssh", "wget --no-check-certificate https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub -O /home/vagrant/.ssh/authorized_keys", "chmod 0600 /home/vagrant/.ssh/authorized_keys", "chown -R vagrant:vagrant /home/vagrant/.ssh", "echo Installing Ansible ...", "DEBIAN_FRONTEND=noninteractive apt install -y ansible", "echo Installing VirtualBox Guest Additions {{ .Version }} ...", "apt install gcc make perl -y", "apt install virtualbox-guest-additions-iso -y", "mkdir /tmp/isomount", "mount -t iso9660 -o loop /usr/share/virtualbox/VBoxGuestAdditions.iso /tmp/isomount", "/tmp/isomount/VBoxLinuxAdditions.run", "echo 'Install Ubuntu desktop ...'", "echo /usr/sbin/lightdm > /etc/X11/default-display-manager", "DEBIAN_FRONTEND=noninteractive apt install -y lightdm", "DEBIAN_FRONTEND=noninteractive apt install -y ubuntu-desktop", "systemctl restart lightdm", "echo Updating/Upgrading ubuntu ...", "DEBIAN_FRONTEND=noninteractive apt update -y && apt upgrade -y"]
  }

  post-processors {
    post-processor "vagrant" {
      keep_input_artifact  = false
      output               = "packer_${var.vm_name}_virtualbox.box"
      vagrantfile_template = "${var.vm_name}.template"
    }
    post-processor "vagrant-cloud" {
      access_token = "${var.cloud_token}"
      box_tag      = "martijnsips/${var.vm_name}"
      version      = "${var.version}"
    }
  }
}
